version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luganodes-backend
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - /app/node_modules